services:
  - type: web
    name: tailor-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: backend/credentials/credentials.json
    rootDir: backend

  - type: web
    name: tailor-frontend
    env: python
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=8080 --server.enableCORS=false
    rootDir: frontend
